// SPDX-License-Identifier: Apache-2.0

//! The onion service contract: what is asked of the daemon, what comes back,
//! and who owns the key. ADR-0003 §6, VCIP-0001.
//!
//! # VayuCell never dials, so VayuCell never speaks Tor
//!
//! Charter Article V.2 is enforced mechanically: nothing in production source
//! opens an outbound connection — the binary listens, and that is all. An onion
//! service therefore cannot be implemented *inside* this process: reaching the
//! Tor network means dialling out. What this module owns instead is the
//! **contract** with the daemon that does the dialling — the system's own
//! `tor`, supervised as a child process like any other surface:
//!
//! - [`Plan`] is what is asked of it, rendered as the exact configuration file
//!   an operator can open and read;
//! - [`read_hostname`] is what comes back, read from the file the daemon
//!   writes once the address exists — and [`Unpublished`] keeps *not written
//!   yet* apart from *unreadable*, because collapsing them would turn "still
//!   bootstrapping" into "something is wrong" or the other way round as
//!   convenience dictated;
//! - [`should_run`] hands the governor the authority ADR-0003 §5 gives it, by
//!   reusing [`crate::ingress::shed_for`] rather than keeping a second opinion
//!   about when high-thermal ingress stops.
//!
//! # The key, and why this crate never touches it
//!
//! The ed25519 identity key *is* the address (ADR-0003 §6). The strongest form
//! of custody available to a process with no crypto code is never to handle
//! the key at all: the daemon generates it inside the hidden-service
//! directory, reads and writes it there, and nothing here opens those files.
//! [`custody_lines`] is where that arrangement is stated to the operator,
//! beside its two permanent costs — rotation breaks every link, and a stolen
//! key cannot be revoked.
//!
//! # What verified still will not mean
//!
//! None of this produces a claim of reachability. ADR-0003 §4 defines verified
//! as a request from outside traversing the path and being served, observed by
//! the cell; reading a hostname file is none of those things. Until that
//! observation machinery exists and has run against a real visitor, the honest
//! report is [`crate::ingress::Reachability::Unverified`] — which is what the
//! panel shows, whatever the daemon says about itself.

use core::fmt::Write as _;

use crate::governor::Level;
use crate::ingress::{self, Mode};

/// How many characters a Tor v3 onion address carries before its `.onion`
/// suffix: base32 of 32 key bytes, a two-byte checksum and the one-byte
/// version.
pub const HOST_LEN: usize = 56;

/// One published port. The virtual port is what a visitor knocks on through
/// the Tor network; the target port is the local listener the request is
/// handed to afterwards.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Mapping {
    /// The port the outside world sees, inside the onion address.
    pub virtual_port: u16,
    /// The local port the request is delivered to. Always reached over
    /// loopback, whatever interface the listener itself bound, because the
    /// daemon connects from the same device.
    pub target_port: u16,
}

/// What is asked of the daemon, in full, so the asking can be read back.
///
/// Everything here is data rather than a side effect: [`Plan::torrc`] renders
/// the exact file, tests pin it byte for byte, and the supervision half in the
/// binary only ever writes what this produced. Nothing configures the daemon
/// that did not pass through a value somebody can print.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Plan {
    /// The hidden-service directory. The daemon generates and holds the
    /// identity key inside it; deleting the directory is how the address is
    /// rotated, and rotating is how every existing link breaks.
    pub data_dir: String,
    /// The published ports, in the order they were asked for.
    pub mappings: Vec<Mapping>,
}

impl Plan {
    /// The configuration file this plan asks the daemon to run under.
    ///
    /// Deterministic in the plan, and written to disk by the binary exactly as
    /// rendered here — an operator diffing the file against this function's
    /// output must always find them identical.
    #[must_use]
    pub fn torrc(&self) -> String {
        let mut out = String::from(
            "# Generated by vayucell. The hidden-service directory named below\n\
             # holds the identity key the daemon generates; nothing else reads\n\
             # it. Deleting that directory is how the address changes: a new\n\
             # directory means a new key, a new .onion name, and every existing\n\
             # link broken. There is no way to rotate that keeps the old\n\
             # address working. ADR-0003 §6.\n\
             \n\
             # This daemon publishes one thing and proxies nothing. Leaving a\n\
             # SOCKS port open would quietly turn every program on this device\n\
             # into a Tor user without anybody deciding to be one.\n\
             SocksPort 0\n",
        );
        out.push_str("\nHiddenServiceDir ");
        out.push_str(&self.data_dir);
        out.push('\n');
        for m in &self.mappings {
            // Writing into an owned String cannot fail; the Result exists for
            // writers that can, and the marker documents the impossibility.
            let _ = writeln!(
                out,
                "HiddenServicePort {} 127.0.0.1:{}",
                m.virtual_port, m.target_port
            );
        }
        // ADR-0003 §10.2: the introduction-point rate limit is on by default.
        // The proof-of-work defence is deliberately NOT requested and never
        // reported as present — whether a given daemon build compiled it in
        // cannot be read back from here, and reporting a defence whose
        // presence was not checked is exactly the lie Article IV.3 forbids.
        out.push_str("HiddenServiceEnableIntroDoSDefense 1\n");
        out
    }

    /// The path of the configuration file the binary writes for this plan.
    ///
    /// Inside [`Plan::data_dir`] deliberately: one directory then holds the
    /// key, the config that names it and the log of what the daemon said, so
    /// `rm -rf` on that one directory is the whole undo — matching how the
    /// rest of this program treats `~/.vayucell`.
    #[must_use]
    pub fn rc_path(&self) -> String {
        format!("{}/torrc", self.data_dir)
    }

    /// The path of the daemon log, beside everything else in the plan.
    ///
    /// When nothing outside can reach the cell, the reason is in this file,
    /// and "look in `<path>`" is the most a program that cannot read minds can
    /// honestly offer.
    #[must_use]
    pub fn log_path(&self) -> String {
        format!("{}/tor.log", self.data_dir)
    }
}

/// The `.onion` address the daemon published for this cell, checked before it
/// is believed.
///
/// Shape-checked, not checksummed: the three checks in [`Hostname::parse`] are
/// exactly what can be verified without crypto code — length, alphabet, and
/// the final character that encodes the protocol version. The embedded
/// checksum is *deliberately not verified*, and the parse error says so rather
/// than implying more was checked than was. A daemon that writes garbage gets
/// refused; a daemon writing a well-formed address it does not own would pass
/// here, and nothing in this module claims otherwise.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Hostname {
    bare: String,
}

impl Hostname {
    /// Validates the contents of a hostname file.
    ///
    /// Surrounding whitespace is trimmed — the file ends with a newline — and
    /// everything after that must be exactly a v3 address, or the error names
    /// which of the three checks failed. The specific reason matters: these
    /// are pinned one seed per rule by the mutation gate, because a test that
    /// asserts only "it was refused" passes even if every rule is deleted but
    /// one.
    ///
    /// # Errors
    ///
    /// Names the failed check: length, character set, or version character.
    pub fn parse(raw: &str) -> Result<Self, String> {
        let candidate = raw.trim();
        if candidate.len() != HOST_LEN {
            return Err(format!(
                "a v3 onion address is {HOST_LEN} characters, and this file \
                 holds {} characters: {:?}",
                candidate.len(),
                limit(candidate, 64)
            ));
        }
        for (i, ch) in candidate.chars().enumerate() {
            if !matches!(ch, 'a'..='z' | '2'..='7') {
                return Err(format!(
                    "character {i} of the address, {ch:?}, is not in the \
                     base32 alphabet an onion address is written in"
                ));
            }
        }
        // The last base32 character encodes the low bits of the trailing
        // version byte, 0x03 — so every v3 address ends in 'd'. A different
        // final character is not another valid encoding; it is not v3.
        if !candidate.ends_with('d') {
            return Err(format!(
                "the address ends in {:?}; a v3 address ends in 'd', and this \
                 project serves v3 or nothing",
                candidate
                    .chars()
                    .last()
                    .map_or(String::new(), |c| c.to_string())
            ));
        }
        Ok(Self {
            bare: candidate.to_owned(),
        })
    }

    /// The address as it is typed: `<56 characters>.onion`.
    #[must_use]
    pub fn url(&self) -> String {
        format!("http://{}.onion/", self.bare)
    }

    /// The bare address, without scheme or suffix.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.bare
    }
}

/// Why no address stands, kept apart because the answers differ.
///
/// *Not yet* is the normal state of a cold start — bootstrap takes minutes on
/// a first run. *Unreadable* is a filesystem answer worth an operator's
/// attention. *Malformed* means something wrote the file that was not the
/// daemon. Reporting all three as "waiting" would bury the third forever.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Unpublished {
    /// No hostname file yet. Normal during bootstrap.
    NotYet(String),
    /// The file is there and would not be read.
    Unreadable(String),
    /// Something was read and it is not an address.
    Malformed(String),
}

impl core::fmt::Display for Unpublished {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::NotYet(why) => write!(f, "no address has been published yet ({why})"),
            Self::Unreadable(why) => write!(f, "the address could not be read: {why}"),
            Self::Malformed(why) => write!(f, "what was published is not an address: {why}"),
        }
    }
}

/// Reads the hostname the daemon publishes, through the same seam every probe
/// uses, so a test can hold the filesystem instead of inhabiting one.
///
/// Absent and unreadable are separated by asking whether the path exists
/// before reading it — the same distinction [`crate::host::Host`] makes
/// reachable and the same one a collapsed `Option` would erase.
///
/// # Errors
///
/// [`Unpublished::NotYet`] while nothing has been written, [`Unpublished::
/// Unreadable`] when the file is there and would not open, [`Unpublished::
/// Malformed`] when what was written is not an address. The three stay
/// distinct all the way out; collapsing them is the defect this return type
/// exists to prevent.
pub fn read_hostname(
    host: &dyn crate::host::Host,
    data_dir: &str,
) -> Result<Hostname, Unpublished> {
    let path = format!("{data_dir}/hostname");
    if !host.exists(&path) {
        return Err(Unpublished::NotYet(format!(
            "{path} does not exist; the daemon has not finished publishing"
        )));
    }
    match host.read(&path) {
        Some(raw) => Hostname::parse(&raw).map_err(Unpublished::Malformed),
        None => Err(Unpublished::Unreadable(format!("{path} could not be read"))),
    }
}

/// Whether the onion mode may run at this governor level.
///
/// Not a second opinion: the question is delegated to
/// [`crate::ingress::shed_for`], which is where ADR-0003 §5 already decided
/// that high-thermal ingress sheds first at DERATED and everything outward-
/// facing stops at PROTECT. Keeping a private answer here would let the two
/// drift until a derated device shed its site but kept heating itself with
/// circuits nobody was visiting.
#[must_use]
pub fn should_run(level: Level) -> bool {
    !ingress::shed_for(level, &[Mode::Onion]).is_empty()
}

/// What the operator is told about the key they cannot see, at the moment the
/// mode is switched on. ADR-0003 §6.
///
/// Said in full the first time, because the moment after publication is the
/// wrong time to learn any of it.
#[must_use]
pub fn custody_lines(data_dir: &str) -> Vec<String> {
    vec![
        format!(
            "the identity key lives in {data_dir}, created and held by the \
             daemon; vayucell never reads it, copies it, or prints it"
        ),
        "backing the key up is backing up the ability to be this site; it \
         belongs in encrypted storage off this device, never in a plain archive"
            .to_owned(),
        "rotating the key means deleting that directory: the address changes \
         and every existing link breaks, with no way to keep the old one \
         working"
            .to_owned(),
        "if the key is ever stolen there is no revocation — the remedy is a \
         new address and telling your audience some other way"
            .to_owned(),
    ]
}

/// The dependency this mode names, per Charter Article VIII.4.
///
/// Itemised rather than implied: the program dependency is the system's own
/// tor daemon, found on PATH, operated by nobody this project controls; beyond
/// it sits the Tor network, a commons — better than a supplier, and still not
/// nothing, which is the correction ADR-0003 §0 already made once.
pub const DAEMON_DEPENDENCY: &str = "your system's tor daemon (found on PATH); \
     beyond it, the Tor network itself — a commons, not a supplier, and still a \
     dependency";

/// Shortens a string for inclusion in an error message.
fn limit(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_owned()
    } else {
        let mut cut = max;
        while !s.is_char_boundary(cut) {
            cut -= 1;
        }
        format!("{}…", &s[..cut])
    }
}
