// SPDX-License-Identifier: Apache-2.0

//! Onion contract tests, in the attacker's voice.
//!
//! The two attacks this module exists to refuse: configuration nobody can
//! read back, and an address that was never checked before being shown to an
//! operator as though it had been. Each validation rule below carries its own
//! seed, because a hostile string that trips several rules proves none of
//! them.

use crate::governor::Level;
use crate::host::FakeHost;
use crate::onion::{
    custody_lines, read_hostname, should_run, Hostname, Mapping, Plan, Unpublished,
    DAEMON_DEPENDENCY,
};

/// A well-formed v3 address: fifty-six base32 characters ending in the
/// version character.
fn valid_address() -> String {
    format!("{}{}", "a".repeat(55), "d")
}

/// A plan publishing one site port.
fn single_mapping() -> Plan {
    Plan {
        data_dir: "/var/lib/vayucell/onion".to_owned(),
        mappings: vec![Mapping {
            virtual_port: 80,
            target_port: 8081,
        }],
    }
}

// ── What is asked of the daemon ───────────────────────────────────────────────

#[test]
fn the_generated_configuration_is_exactly_what_is_documented() {
    // Pinned byte for byte. A "contains" assertion would let a stray extra
    // directive ship without any test noticing; an operator diffing the file
    // on disk against this function must find them identical.
    let expected = "\
# Generated by vayucell. The hidden-service directory named below\n\
# holds the identity key the daemon generates; nothing else reads\n\
# it. Deleting that directory is how the address changes: a new\n\
# directory means a new key, a new .onion name, and every existing\n\
# link broken. There is no way to rotate that keeps the old\n\
# address working. ADR-0003 §6.\n\
\n\
# This daemon publishes one thing and proxies nothing. Leaving a\n\
# SOCKS port open would quietly turn every program on this device\n\
# into a Tor user without anybody deciding to be one.\n\
SocksPort 0\n\
\n\
HiddenServiceDir /var/lib/vayucell/onion\n\
HiddenServicePort 80 127.0.0.1:8081\n\
HiddenServiceEnableIntroDoSDefense 1\n";
    assert_eq!(single_mapping().torrc(), expected);
}

#[test]
fn the_published_daemon_proxies_nothing_else_on_the_device() {
    // SocksPort 0 is the least-privilege line in the file. Dropping it would
    // leave the daemon's default behaviour in place — a SOCKS listener every
    // local program could ride — and no other test here would notice.
    let rc = single_mapping().torrc();
    assert!(
        rc.lines().any(|l| l.trim() == "SocksPort 0"),
        "the generated configuration must switch the proxy port off:\n{rc}"
    );
}

#[test]
fn introduction_dos_defence_is_asked_for_by_default() {
    // ADR-0003 §10 open decision 2: the rate limit is on unless somebody
    // turns it off in code where the turn is visible. The proof-of-work
    // defence is deliberately absent from this assertion — whether the
    // daemon build compiled it in cannot be read back from here, so it is
    // never requested and never reported either way.
    let rc = single_mapping().torrc();
    assert!(
        rc.contains("HiddenServiceEnableIntroDoSDefense 1"),
        "the introduction rate limit must be requested by default:\n{rc}"
    );
}

#[test]
fn every_published_port_reaches_its_own_local_listener() {
    let plan = Plan {
        data_dir: "/d".to_owned(),
        mappings: vec![
            Mapping {
                virtual_port: 80,
                target_port: 8081,
            },
            Mapping {
                virtual_port: 8080,
                target_port: 8082,
            },
        ],
    };
    let rc = plan.torrc();
    assert!(rc.contains("HiddenServicePort 80 127.0.0.1:8081"), "{rc}");
    assert!(rc.contains("HiddenServicePort 8080 127.0.0.1:8082"), "{rc}");
}

#[test]
fn the_config_and_the_log_live_inside_the_key_directory() {
    // One directory holds the key, the config that names it and the log, so
    // deleting that directory is the whole undo — the same shape as
    // `rm -rf ~/.vayucell` elsewhere in this program.
    let plan = single_mapping();
    assert_eq!(plan.rc_path(), "/var/lib/vayucell/onion/torrc");
    assert_eq!(plan.log_path(), "/var/lib/vayucell/onion/tor.log");
}

// ── What comes back ───────────────────────────────────────────────────────────

#[test]
fn a_well_formed_address_is_accepted_and_typed_as_one() {
    let h = Hostname::parse(&valid_address()).expect("a valid address parses");
    assert_eq!(h.as_str(), valid_address());
    assert_eq!(h.url(), format!("http://{}.onion/", valid_address()));
}

#[test]
fn surrounding_whitespace_is_not_part_of_the_address() {
    // The daemon writes a trailing newline. Refusing it would make the common
    // case the failure case.
    let padded = format!("  {}\n", valid_address());
    assert!(Hostname::parse(&padded).is_ok());
}

#[test]
fn an_address_of_the_wrong_length_is_refused_with_the_count() {
    // One seed for the length rule alone: right alphabet, right version
    // character, one character short. A seed that broke several rules would
    // leave this assertion green even after the length check was deleted.
    let short = format!("{}d", "a".repeat(54));
    let e = Hostname::parse(&short).expect_err("54 characters must be refused");
    assert!(e.contains("56"), "{e}");
    assert!(e.contains("55"), "{e}");
}

#[test]
fn a_character_outside_base32_is_refused_and_named_by_position() {
    // '1' is not in the onion alphabet — base32 skips it precisely because
    // it is mistaken for 'l' when an address is copied by hand.
    let mut bad = valid_address();
    bad.replace_range(10..11, "1");
    let e = Hostname::parse(&bad).expect_err("'1' is not base32");
    assert!(e.contains("10"), "{e}");
    assert!(e.contains("'1'"), "{e}");
}

#[test]
fn an_uppercase_address_is_refused_rather_than_normalised() {
    // Tor writes lowercase. Silently accepting upper case would publish one
    // spelling while the operator pastes another, and .onion comparison is
    // byte-exact everywhere that matters.
    let mut bad = valid_address();
    bad.replace_range(0..1, "A");
    let e = Hostname::parse(&bad).expect_err("uppercase is not the published form");
    assert!(e.contains("base32"), "{e}");
}

#[test]
fn an_address_that_does_not_end_in_v3s_version_char_is_refused() {
    // The trailing 'd' encodes protocol version 3. Ending in anything else
    // is not another rendering of v3; serving it would mean publishing an
    // address this project does not understand.
    let mut bad = valid_address();
    bad.replace_range(55..56, "e");
    let e = Hostname::parse(&bad).expect_err("'e' does not encode version 3");
    assert!(e.contains("'d'"), "{e}");
    assert!(e.contains("v3"), "{e}");
}

#[test]
fn empty_contents_are_refused_as_what_they_are() {
    let e = Hostname::parse("").expect_err("an empty file holds no address");
    assert!(e.contains("0 characters"), "{e}");
}

#[test]
fn a_long_nonsense_file_is_summarised_rather_than_quoted_in_full() {
    // The failure lands in a terminal and a log. Echoing kilobytes of
    // whatever was in the file buries the sentence that matters.
    let junk = "x".repeat(500);
    let e = Hostname::parse(&junk).expect_err("junk must be refused");
    assert!(e.len() < 300, "{e}");
}

// ── Reading what the daemon published ─────────────────────────────────────────

#[test]
fn a_hostname_nobody_has_written_yet_is_not_yet_not_broken() {
    // Bootstrap takes minutes on a cold start. Calling that state a failure
    // would have the supervisor restart a working daemon, over and over, for
    // exactly as long as it was doing the thing it was asked to do.
    let host = FakeHost::new();
    let e = read_hostname(&host, "/d").expect_err("nothing published yet");
    assert!(matches!(e, Unpublished::NotYet(_)), "{e:?}");
    assert!(e.to_string().contains("does not exist"), "{e}");
}

#[test]
fn a_hostname_that_cannot_be_read_is_not_called_absent() {
    // Present and unreadable is a filesystem answer worth an operator's
    // attention. Collapsing it into "not yet" would wait forever on a daemon
    // that already finished, and into "malformed" would send them hunting
    // for corruption that is really a permission.
    let host = FakeHost::new().with_unreadable("/d/hostname");
    let e = read_hostname(&host, "/d").expect_err("unreadable must not pass");
    assert!(matches!(e, Unpublished::Unreadable(_)), "{e:?}");
    assert!(e.to_string().contains("could not be read"), "{e}");
}

#[test]
fn garbage_where_an_address_should_be_is_malformed_not_missing() {
    let host = FakeHost::new().with_file("/d/hostname", "not-an-address");
    let e = read_hostname(&host, "/d").expect_err("junk must not pass");
    assert!(matches!(e, Unpublished::Malformed(_)), "{e:?}");
}

#[test]
fn the_published_address_is_read_back_through_the_seam() {
    let host = FakeHost::new().with_file(
        "/d/hostname",
        &format!("{valid}\n", valid = valid_address()),
    );
    let h = read_hostname(&host, "/d").expect("a written address reads back");
    assert_eq!(h.url(), format!("http://{}.onion/", valid_address()));
}

// ── The governor's authority ──────────────────────────────────────────────────

#[test]
fn normal_leaves_the_onion_running() {
    assert!(should_run(Level::Normal));
}

#[test]
fn a_derated_governor_sheds_the_onion_before_it_sheds_serving() {
    // High thermal class sheds FIRST — ADR-0003 §5. This is the delegation
    // to ingress::shed_for, asserted here so a local re-implementation that
    // "simplifies" the dependency cannot silently keep circuits burning on a
    // device that is already too hot.
    assert!(!should_run(Level::Derated));
}

#[test]
fn protect_and_halt_stop_the_onion() {
    assert!(!should_run(Level::Protect));
    assert!(!should_run(Level::Halt));
}

// ── What the operator is told ─────────────────────────────────────────────────

#[test]
fn the_custody_story_names_its_directory_rotation_and_lack_of_revocation() {
    // Three permanent facts about the key, said before the mode starts rather
    // than discovered after something goes wrong: where it lives, what
    // rotating costs, and that theft has no undo. ADR-0003 §6.
    let lines = custody_lines("/var/lib/vayucell/onion");
    let joined = lines.join("\n");
    assert!(
        lines.iter().any(|l| l.contains("/var/lib/vayucell/onion")),
        "{joined}"
    );
    assert!(joined.contains("never reads it"), "{joined}");
    assert!(joined.contains("every existing link breaks"), "{joined}");
    assert!(joined.contains("no revocation"), "{joined}");
    assert!(joined.contains("encrypted"), "{joined}");
}

#[test]
fn the_dependency_is_itemised_not_implied() {
    // Charter Article VIII.4 owes the operator an itemised account of every
    // external dependency. "Tor" alone is not an account: it hides a program
    // that must exist on PATH behind a network.
    assert!(
        DAEMON_DEPENDENCY.contains("tor daemon"),
        "{DAEMON_DEPENDENCY}"
    );
    assert!(DAEMON_DEPENDENCY.contains("PATH"), "{DAEMON_DEPENDENCY}");
    assert!(DAEMON_DEPENDENCY.contains("commons"), "{DAEMON_DEPENDENCY}");
}
